import { View, Text, StyleSheet } from "react-native";
import React from "react";

export default StyleSheet.create({
  Search_Container: {
    width: "100%",
    flexDirection: "row",
    paddingTop: 10,
    paddingHorizontal: 5,
  },
  Search_Container_Switch: {
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  Search_Container_Switch_Text: {
    fontSize: 12,
    color: "black",
    fontWeight: 500,
  },
  Search_Container_Search_Box: {
    flex: 1,
    backgroundColor: "#F1F1F1",
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#c2c2c2",
  },
  Search_Container_Search_Box_Image: {
    flex: 0.1,
    justifyContent: "center",
    alignItems: "center",
  },
  Search_Container_Search_Box_Text: {
    flex: 0.7,
    justifyContent: "center",
    alignContent: "center",
  },
  Search_Container_Search_Box_Icon_Image: {
    flex: 0.15,
    justifyContent: "center",
    alignItems: "center",
  },
  Search_Container_Search_Box_Icon_Image_Size: {
    height: 25,
    width: 25,
    tintColor: "#000",
  },
  Margin_Top_20: {
    marginTop: 20,
  },

  Three_Section_Container: {
    flexDirection: "row",
    flex: 1,
    marginHorizontal: 10,
  },
  Three_Section_Container_Item: {
    margin: 5,
    borderWidth: 0.5,
    borderColor: "grey",
    borderRadius: 10,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  Three_Section_Container_Item_Image: {
    height: 80,
    width: "100%",
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  Three_Section_Container_Item_Title: {
    alignContent: "center",
    alignSelf: "center",
    fontWeight: 500,
    color: "black",
  },
  Three_Section_Container_Item_SubTitle: {
    alignContent: "center",
    alignSelf: "center",
    fontWeight: 600,
    color: "black",
    fontSize: 18,
  },

  Two_Section_Container: { flexDirection: "row", flex: 1, marginTop: 20 },
  Two_Section_Container_Item: {
    flex: 0.5,
    marginHorizontal: 10,
    backgroundColor: "#99e6fc",
    borderWidth: 0.5,

    borderRadius: 10,
  },
  Two_Section_Container_Item_Image: {
    height: 170,
    width: "100%",
    borderWidth: 1,
    // borderColor: "grey",
    borderRadius: 10,
  },
  Two_Section_Container_Item_Title: {
    fontSize: 16,
    fontFamily: "Lobster-Regular",
    color: "black",
    fontWeight: 600,
    marginLeft: 5,
    marginTop: 5,
  },
  Two_Section_Container_Item_SubTitle: {
    fontSize: 12,
    color: "black",
    fontWeight: 300,
    marginHorizontal: 5,
    marginTop: 5,
  },
  Two_Section_Container_Item_Price: {
    fontSize: 14,
    color: "black",
    fontWeight: 600,
    textAlign: "center",
    marginTop: 5,
  },
  Sponsored_Container: {
    height: 50,
    marginVertical: 10,
    backgroundColor: "white",
    justifyContent: "center",
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    elevation: 5,
    borderColor: "grey",
  },
  Sponsored_Container_Text: {
    fontSize: 20,
    color: "black",
    fontFamily: "ChivoMono-Black",
    marginLeft: 10,
    fontWeight: 500,
  },
  Sponsored_Container_Item: {
    flex: 1,
    flexDirection: "row",
    marginHorizontal: 5,
  },
  Sponsored_Container_Style: {
    fontFamily: "Lobster-Regular",
    borderWidth: 0.5,
    borderColor: "grey",
    borderRadius: 10,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  Sponsored_Container_Item_Image: {
    height: 120,
    width: "100%",
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  Sponsored_Container_Item_Title: {
    alignContent: "center",
    alignSelf: "center",
    fontWeight: 400,
    color: "black",
    fontSize: 12,
  },
  Sponsored_Container_Item_Offer: {
    fontFamily: "Lobster-Regular",
    alignContent: "center",
    alignSelf: "center",
    fontWeight: 600,
    color: "black",
    fontSize: 14,
  },
});
