import { StyleSheet } from "react-native";

export default StyleSheet.create({
  Search_Box_Container: {
    flexDirection: "row",
    flex: 0.1,
    borderWidth: 1,
    margin: 15,
  },
  Search_Box_Search_Icon: {
    flex: 0.2,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
  },
  Search_Box_Mic_Icon: {
    flex: 0.2,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
  },
  Category_Image: {
    borderWidth: 2,
    borderColor: "#cfe1ff",
    borderRadius: 5,
    height: 100,
    width: 100,
    alignSelf: "center",
    justifyContent: "center",
    alignContent: "center",
  },
  Category_Text: {
    color: "black",
    alignContent: "center",
    justifyContent: "center",
    alignContent: "center",
    fontSize: 12,
    fontWeight: 700,
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 20,
  },
  Limited_Time_Offer_Section: {
    marginTop: 20,
    paddingVertical: 20,
    alignContent: "center",
    justifyContent: "center",
    borderWidth: 0,
  },
  Common_Text_Style: {
    fontSize: 16,
    color: "black",
    fontWeight: 500,
  },
  Location_Button_Section: {
    flex: 0.3,
    margin: 20,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    borderWidth: 0.5,
  },
  Common_Text_Style_two: {
    fontSize: 14,
    color: "black",
  },
  Limited_Time_Offer_Section_Item_Container: {
    flex: 1,
    flexDirection: "row",
    marginVertical: 2,
    elevation: 1,
    backgroundColor: "white",
  },
  Limited_Time_Offer_Section_Item_Image: {
    flex: 0.4,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  Limited_Time_Offer_Section_order_Price: {
    fontSize: 16,
    color: "black",
    fontWeight: 500,
    marginVertical: 5,
  },
  Limited_Time_Offer_Section_Order_Price_Off: {
    flex: 0.3,
    paddingVertical: 5,
    backgroundColor: "#26a541",
    alignItems: "center",
  },

  Limited_Time_Offer_Section_Add_To_Cart_Container: {
    flex: 0.4,
    justifyContent: "center",
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 1,
    borderBottomWidth: 2,
    borderColor: "#2874f0",
  },

  Limited_Time_Offer_Section_Add_To_Cart_Icon: {
    flex: 0.3,
    justifyContent: "center",
    borderTopWidth: 2,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#2874f0",
  },
  Easy_Ordering_Container: {
    borderWidth: 0,
    marginVertical: 10,
    backgroundColor: "#C6F8C6",
  },
  Easy_Ordering_Text_Container: {
    marginVertical: 20,
    paddingVertical: 20,
    flexDirection: "row",
  },
  Easy_Ordering_View_All_Button: {
    flex: 0.2,
    backgroundColor: "#2874f0",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
  },
  Easy_Ordering_Item_Container: {
    marginHorizontal: 10,
    backgroundColor: "#99e6fc",
    borderWidth: 0.5,
    width: 150,

    borderRadius: 10,
  },
  Easy_Ordering_Item_Container_Image: {
    height: 170,
    width: "100%",
    borderWidth: 1,
    borderColor: "grey",
    borderRadius: 10,
  },
  Easy_Ordering_Item_Container_Title: {
    fontSize: 14,
    color: "black",
    fontWeight: 600,
    marginHorizontal: 10,
    marginTop: 5,
  },
  Easy_Ordering_Container_SubTitle: {
    fontSize: 12,
    color: "black",
    fontWeight: 300,
    marginHorizontal: 10,
    marginTop: 5,
  },
  Easy_Ordering_Container_Weight: {
    fontSize: 12,
    color: "black",
    fontWeight: 300,
    marginHorizontal: 10,
    marginVertical: 5,
  },
  Easy_Ordering_Container_Price: {
    fontSize: 14,
    color: "black",
    fontWeight: 600,
    marginLeft: 10,
  },
  Easy_Ordering_Add_to_Cart_Container: {
    flex: 1,
    marginVertical: 20,
    flexDirection: "row",
    alignContent: "center",
    justifyContent: "center",
  },
  Easy_Ordering_Add_to_Cart_Container_Item: {
    flex: 0.4,
    justifyContent: "center",
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderRightWidth: 1,
    borderBottomWidth: 2,
    borderColor: "#2874f0",
  },
  Easy_Ordering_Add_to_Cart_Container_Text: {
    fontSize: 16,
    textAlign: "center",
    color: "black",
    fontWeight: 600,
  },
  Easy_Ordering_Add_to_Cart_Container_Icon: {
    flex: 0.3,
    justifyContent: "center",
    borderTopWidth: 2,
    borderRightWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#2874f0",
  },
});
